### ISSUE TITLE
投票機能用のAPI(stack)を作成する

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/dreamkast-functions#4]
一旦こんな感じ...? 

## APIの仕様

- METHOD：GET
- PATH：`/{event}/talks/{talkId}/vote`
- 動作：
  - クライアントのIPを取得
  -  NGとか返さずひたすらdynamodbのデータ上書きしていく
    - dynamodbにすでにIPがあればNG（？）を返すとかでもできそうだけど
    - いったん無しの方向でいいかな 🤔 
  - 下記フォーマットでdynamodbに保存
    - event, globalIP, talkId

**Comment by jacopen** [comment]
PATHのイメージはあってます。
メソッドは空ボディのPOSTがいいかなと
